[workspace]
  members = ["interoplib", "objc"]
  build-members = []
  test-members = []
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  target-dir = ""

[dependencies]
interoplib = { path = "interoplib" }

[profile.customized-option]
  cfg_darwin_objc = "${TARGET_OPTION} ${SYSROOT_OPTION} --int-overflow wrapping -lobjc"
  cfg_linux_objc = "${TARGET_OPTION} ${SYSROOT_OPTION} --int-overflow wrapping"
