// Copyright (c) Huawei Technologies Co., Ltd. 2025. All rights reserved.
// This source file is part of the Cangjie project, licensed under Apache-2.0
// with Runtime Library Exception.
//
// See https://cangjie-lang.cn/pages/LICENSE for license information.

[workspace]
  members = ["interoplib", "objc"]
  build-members = []
  test-members = []
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  target-dir = ""

[dependencies]
interoplib = { path = "interoplib" }

[profile.customized-option]
  cfg_darwin_objc = "${TARGET_OPTION} ${SYSROOT_OPTION} --int-overflow wrapping -lobjc"
  cfg_linux_objc = "${TARGET_OPTION} ${SYSROOT_OPTION} --int-overflow wrapping"
