[package]
  cjc-version = "0.65.1"
  name = "objc"
  description = "nothing here"
  version = "1.0.0"
  target-dir = ""
  src-dir = ""
  output-type = "dynamic"
  compile-option = ""
  override-compile-option = ""
  link-option = ""
  package-configuration = {}

[dependencies]

[profile.customized-option]
  cfg_darwin_objc = "${TARGET_OPTION} ${SYSROOT_OPTION} --int-overflow wrapping -lobjc"
  cfg_linux_objc = "${TARGET_OPTION} ${SYSROOT_OPTION} --int-overflow wrapping"